async function Module(moduleArg={}){var moduleRtn;var h=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,r="object"==typeof process&&process.versions?.node&&"renderer"!=process.type;if(r){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var ca=import.meta.url,u="",da,w;
if(r){var fs=require("fs");ca.startsWith("file:")&&(u=require("path").dirname(require("url").fileURLToPath(ca))+"/");w=a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a)};da=async a=>{a=y(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2)}else if(aa||ba){try{u=(new URL(".",ca)).href}catch{}ba&&(w=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});da=async a=>{if(y(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;
e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var A=console.error.bind(console),B,ea=!1,y=a=>a.startsWith("file://"),fa,ha,C,ia,D,E,G,H,I,ka,la,ma,na,oa=!1;
function pa(){var a=C.buffer;ia=new Int8Array(a);E=new Int16Array(a);D=new Uint8Array(a);G=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);ka=new Float32Array(a);la=new Float64Array(a);ma=new BigInt64Array(a);na=new BigUint64Array(a)}var J=0,K=null;function qa(a){h.onAbort?.(a);a="Aborted("+a+")";A(a);ea=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ha?.(a);throw a;}var ra;
async function sa(a){if(!B)try{var b=await da(a);return new Uint8Array(b)}catch{}if(a==ra&&B)a=new Uint8Array(B);else if(w)a=w(a);else throw"both async and sync fetching of the wasm failed";return a}async function ta(a,b){try{var c=await sa(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),qa(d)}}
async function ua(a){var b=ra;if(!B&&"function"==typeof WebAssembly.instantiateStreaming&&!y(b)&&!r)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return ta(b,a)}var va=a=>{for(;0<a.length;)a.shift()(h)},wa=[],xa=[],ya=()=>{var a=h.preRun.shift();xa.push(a)};class za{constructor(a){this.K=a-24}}var Aa=0,Ba=0,L={},Ca=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};
function M(a){return this.F(I[a>>2])}
var N={},O={},P={},Da=class extends Error{constructor(a){super(a);this.name="InternalError"}},Ea=(a,b,c)=>{function d(f){f=c(f);if(f.length!==a.length)throw new Da("Mismatched type converter count");for(var m=0;m<a.length;++m)Q(a[m],f[m])}a.forEach(f=>P[f]=b);var e=Array(b.length),g=[],k=0;b.forEach((f,m)=>{O.hasOwnProperty(f)?e[m]=O[f]:(g.push(f),N.hasOwnProperty(f)||(N[f]=[]),N[f].push(()=>{e[m]=O[f];++k;k===g.length&&d(e)}))});0===g.length&&d(e)},R=a=>{for(var b="";;){var c=D[a++];if(!c)return b;
b+=String.fromCharCode(c)}},S=class extends Error{constructor(a){super(a);this.name="BindingError"}},Fa=a=>{throw new S(a);};function Ga(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(O.hasOwnProperty(a)){if(c.R)return;throw new S(`Cannot register type '${d}' twice`);}O[a]=b;delete P[a];N.hasOwnProperty(a)&&(b=N[a],delete N[a],b.forEach(e=>e()))}function Q(a,b,c={}){return Ga(a,b,c)}
var Ha=(a,b,c)=>{switch(b){case 1:return c?d=>ia[d]:d=>D[d];case 2:return c?d=>E[d>>1]:d=>G[d>>1];case 4:return c?d=>H[d>>2]:d=>I[d>>2];case 8:return c?d=>ma[d>>3]:d=>na[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ia=[],T=[0,1,,1,null,1,!0,1,!1,1],Ja=a=>{9<a&&0===--T[a+1]&&(T[a]=void 0,Ia.push(a))},U=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return T[a]},V=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=
Ia.pop()||T.length;T[b]=a;T[b+1]=1;return b}},Ka={name:"emscripten::val",F:a=>{var b=U(a);Ja(a);return b},G:(a,b)=>V(b),J:M,H:null},La=(a,b)=>{switch(b){case 4:return function(c){return this.F(ka[c>>2])};case 8:return function(c){return this.F(la[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}};function Ma(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
var Pa=(a,b)=>{if(void 0===h[a].I){var c=h[a];h[a]=function(...d){if(!h[a].I.hasOwnProperty(d.length))throw new S(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${h[a].I})!`);return h[a].I[d.length].apply(this,d)};h[a].I=[];h[a].I[c.L]=c}},Qa=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].I&&void 0!==h[a].I[c])throw new S(`Cannot register public name '${a}' twice`);Pa(a,a);if(h[a].I.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].I[c]=b}else h[a]=b,h[a].L=c},Ra=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(I[b+4*d>>2]);return c},Sa=[],Ta,W=(a,b)=>{a=R(a);var c;(c=Sa[b])||(Sa[b]=c=Ta.get(b));if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};class Ua extends Error{}
var Wa=a=>{a=Va(a);var b=R(a);X(a);return b},Xa=(a,b)=>{function c(g){e[g]||O[g]||(P[g]?P[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Ua(`${a}: `+d.map(Wa).join([", "]));},Ya=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Za="undefined"!=typeof TextDecoder?new TextDecoder:void 0,$a=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},ab=(a=0,b)=>{var c=D;b=$a(c,a,b,!0);if(16<b-a&&c.buffer&&Za)return Za.decode(c.subarray(a,b));for(var d=
"";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var k=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|k:(e&7)<<18|g<<12|k<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},bb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,cb=(a,b,c)=>{a>>=1;b=$a(G,a,b/2,c);if(16<b-a&&bb)return bb.decode(G.subarray(a,b));for(c="";a<b;++a)c+=String.fromCharCode(G[a]);
return c},db=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)E[b>>1]=a.charCodeAt(e),b+=2;E[b>>1]=0;return b-d},eb=a=>2*a.length,fb=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var g=I[a+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},gb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.codePointAt(e);65535<g&&e++;H[b>>2]=g;b+=4;if(b+4>c)break}H[b>>2]=0;return b-d},hb=a=>{for(var b=0,c=
0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},ib=[],jb=a=>{var b=ib.length;ib.push(a);return b},kb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,g=I[b+4*d>>2],k=O[g];if(void 0===k)throw a=`${`parameter ${d}`} has unknown type ${Wa(g)}`,new S(a);c[e]=k}return c},lb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(I[b>>2]=V(d));return a},mb={},nb=a=>{var b=mb[a];return void 0===b?R(a):b};h.printErr&&(A=h.printErr);h.wasmBinary&&(B=h.wasmBinary);
var ob,Va,X,pb={h:(a,b,c)=>{var d=new za(a);I[d.K+16>>2]=0;I[d.K+4>>2]=b;I[d.K+8>>2]=c;Aa=a;Ba++;throw Aa;},p:()=>qa(""),o:a=>{var b=L[a];delete L[a];var c=b.elements,d=c.length,e=c.map(f=>f.P).concat(c.map(f=>f.V)),g=b.S,k=b.T;Ea([a],e,f=>{c.forEach((m,l)=>{var p=f[l],x=m.N,n=m.O,z=f[l+d],F=m.U,Y=m.W;m.read=q=>p.F(x(n,q));m.write=(q,v)=>{var t=[];F(Y,q,z.G(t,v));Ca(t)}});return[{name:b.name,F:m=>{for(var l=Array(d),p=0;p<d;++p)l[p]=c[p].read(m);k(m);return l},G:(m,l)=>{if(d!==l.length)throw new TypeError(`Incorrect number of tuple elements for ${b.name}: expected=${d}, actual=${l.length}`);
for(var p=g(),x=0;x<d;++x)c[x].write(p,l[x]);null!==m&&m.push(k,p);return p},J:M,H:k}]})},k:(a,b,c,d,e)=>{b=R(b);d=0n===d;let g=k=>k;if(d){const k=8*c;g=f=>BigInt.asUintN(k,f);e=g(e)}Q(a,{name:b,F:g,G:(k,f)=>{"number"==typeof f&&(f=BigInt(f));return f},J:Ha(b,c,!d),H:null})},u:(a,b,c,d)=>{b=R(b);Q(a,{name:b,F:function(e){return!!e},G:function(e,g){return g?c:d},J:function(e){return this.F(D[e])},H:null})},r:a=>Q(a,Ka),j:(a,b,c)=>{b=R(b);Q(a,{name:b,F:d=>d,G:(d,e)=>e,J:La(b,c),H:null})},y:(a,b,c,d,
e,g,k)=>{var f=Ra(b,c);a=R(a);a=Ya(a);e=W(d,e);Qa(a,function(){Xa(`Cannot call ${a} due to unbound types`,f)},b-1);Ea([],f,m=>{var l=[m[0],null].concat(m.slice(1));m=a;var p=a;var x=e,n=l.length;if(2>n)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var z=null!==l[1]&&!1,F=Ma(l),Y=!l[0].M,q=l[0],v=l[1];x=[p,Fa,x,g,Ca,q.F.bind(q),v?.G.bind(v)];for(q=2;q<n;++q)v=l[q],x.push(v.G.bind(v));if(!F)for(q=z?1:2;q<l.length;++q)null!==l[q].H&&x.push(l[q].H);F=Ma(l);
q=l.length-2;var t=[];v=["fn"];z&&v.push("thisWired");for(n=0;n<q;++n)t.push(`arg${n}`),v.push(`arg${n}Wired`);t=t.join(",");v=v.join(",");t=`return function (${t}) {\n`;F&&(t+="var destructors = [];\n");var Na=F?"destructors":"null",ja="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");z&&(t+=`var thisWired = toClassParamWire(${Na}, this);\n`);for(n=0;n<q;++n){var Oa=`toArg${n}Wire`;t+=`var arg${n}Wired = ${Oa}(${Na}, arg${n});\n`;ja.push(Oa)}t+=(Y||k?
"var rv = ":"")+`invoker(${v});\n`;if(F)t+="runDestructors(destructors);\n";else for(n=z?1:2;n<l.length;++n)z=1===n?"thisWired":"arg"+(n-2)+"Wired",null!==l[n].H&&(t+=`${z}_dtor(${z});\n`,ja.push(`${z}_dtor`));Y&&(t+="var ret = fromRetWire(rv);\nreturn ret;\n");l=(new Function(ja,t+"}\n"))(...x);p=Object.defineProperty(l,"name",{value:p});l=b-1;if(!h.hasOwnProperty(m))throw new Da("Replacing nonexistent public symbol");void 0!==h[m].I&&void 0!==l?h[m].I[l]=p:(h[m]=p,h[m].L=l);return[]})},b:(a,b,c,
d,e)=>{b=R(b);let g=f=>f;if(0===d){var k=32-8*c;g=f=>f<<k>>>k;e=g(e)}Q(a,{name:b,F:g,G:(f,m)=>m,J:Ha(b,c,0!==d),H:null})},a:(a,b,c)=>{function d(g){return new e(ia.buffer,I[g+4>>2],I[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=R(c);Q(a,{name:c,F:d,J:d},{R:!0})},t:(a,b)=>{b=R(b);Q(a,{name:b,F(c){var d=(d=c+4)?ab(d,I[c>>2]):"";X(c);return d},G(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e,
g="string"==typeof d;if(!(g||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");var k;if(g)for(e=k=0;e<d.length;++e){var f=d.charCodeAt(e);127>=f?k++:2047>=f?k+=2:55296<=f&&57343>=f?(k+=4,++e):k+=3}else k=d.length;e=k;k=ob(4+e+1);f=k+4;I[k>>2]=e;if(g){if(g=f,f=e+1,e=D,0<f){f=g+f-1;for(var m=0;m<d.length;++m){var l=d.codePointAt(m);if(127>=l){if(g>=f)break;e[g++]=l}else if(2047>=l){if(g+1>=f)break;e[g++]=192|l>>6;e[g++]=128|l&63}else if(65535>=l){if(g+
2>=f)break;e[g++]=224|l>>12;e[g++]=128|l>>6&63;e[g++]=128|l&63}else{if(g+3>=f)break;e[g++]=240|l>>18;e[g++]=128|l>>12&63;e[g++]=128|l>>6&63;e[g++]=128|l&63;m++}}e[g]=0}}else D.set(d,f);null!==c&&c.push(X,k);return k},J:M,H(c){X(c)}})},g:(a,b,c)=>{c=R(c);if(2===b){var d=cb;var e=db;var g=eb}else d=fb,e=gb,g=hb;Q(a,{name:c,F:k=>{var f=d(k+4,I[k>>2]*b,!0);X(k);return f},G:(k,f)=>{if("string"!=typeof f)throw new S(`Cannot pass non-string to C++ string type ${c}`);var m=g(f),l=ob(4+m+b);I[l>>2]=m/b;e(f,
l+4,m+b);null!==k&&k.push(X,l);return l},J:M,H(k){X(k)}})},s:(a,b,c,d,e,g)=>{L[a]={name:R(b),S:W(c,d),T:W(e,g),elements:[]}},i:(a,b,c,d,e,g,k,f,m)=>{L[a].elements.push({P:b,N:W(c,d),O:e,V:g,U:W(k,f),W:m})},v:(a,b)=>{b=R(b);Q(a,{M:!0,name:b,F:()=>{},G:()=>{}})},f:(a,b,c)=>{var [d,...e]=kb(a,b);b=d.G.bind(d);var g=e.map(m=>m.J.bind(m));a--;var k={toValue:U};a=g.map((m,l)=>{var p=`argFromPtr${l}`;k[p]=m;return`${p}(args${l?"+"+8*l:""})`});switch(c){case 0:var f="toValue(handle)";break;case 2:f="new (toValue(handle))";
break;case 3:f="";break;case 1:k.getStringOrSymbol=nb,f="toValue(handle)[getStringOrSymbol(methodName)]"}f+=`(${a})`;d.M||(k.toReturnWire=b,k.emval_returnValue=lb,f=`return emval_returnValue(toReturnWire, destructorsRef, ${f})`);f=`return function (handle, methodName, destructorsRef, args) {\n  ${f}\n  }`;c=(new Function(Object.keys(k),f))(...Object.values(k));f=`methodCaller<(${e.map(m=>m.name)}) => ${d.name}>`;return jb(Object.defineProperty(c,"name",{value:f}))},c:Ja,m:(a,b)=>{a=U(a);b=U(b);return V(a[b])},
l:a=>{9<a&&(T[a+1]+=1)},e:(a,b,c,d,e)=>ib[a](b,c,d,e),n:()=>V([]),x:a=>{a=U(a);for(var b=Array(a.length),c=0;c<a.length;c++)b[c]=a[c];return V(b)},w:a=>V(nb(a)),d:a=>{var b=U(a);Ca(b);Ja(a)},q:a=>{var b=D.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-C.buffer.byteLength+65535)/65536|0;try{C.grow(d);pa();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1}},Z=await (async function(){function a(c){Z=
c.exports;C=Z.z;pa();Ta=Z.B;c=Z;ob=c.C;Va=c.D;X=c.E;J--;h.monitorRunDependencies?.(J);0==J&&K&&(c=K,K=null,c());return Z}J++;h.monitorRunDependencies?.(J);var b={a:pb};if(h.instantiateWasm)return new Promise(c=>{h.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ra??=h.locateFile?h.locateFile?h.locateFile("worker_wasm.wasm",u):u+"worker_wasm.wasm":(new URL("worker_wasm.wasm",import.meta.url)).href;return a((await ua(b)).instance)}());
function qb(){function a(){h.calledRun=!0;if(!ea){oa=!0;Z.A();fa?.(h);h.onRuntimeInitialized?.();if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var b=h.postRun.shift();wa.push(b)}va(wa)}}if(0<J)K=qb;else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)ya();va(xa);0<J?K=qb:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),1);a()},1)):a()}}
if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();qb();oa?moduleRtn=h:moduleRtn=new Promise((a,b)=>{fa=a;ha=b});
;return moduleRtn}export default Module;
