async function Module(moduleArg={}){var moduleRtn;var n=moduleArg,aa="object"==typeof window,ba="undefined"!=typeof WorkerGlobalScope,ca="object"==typeof process&&process.versions?.node&&"renderer"!=process.type;if(ca){const {createRequire:b}=await import("module");var require=b(import.meta.url)}var da=import.meta.url,p="",ea,q;
if(ca){var fs=require("fs");da.startsWith("file:")&&(p=require("path").dirname(require("url").fileURLToPath(da))+"/");q=b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b)};ea=async b=>{b=t(b)?new URL(b):b;return fs.readFileSync(b,void 0)};process.argv.slice(2)}else if(aa||ba){try{p=(new URL(".",da)).href}catch{}ba&&(q=b=>{var a=new XMLHttpRequest;a.open("GET",b,!1);a.responseType="arraybuffer";a.send(null);return new Uint8Array(a.response)});ea=async b=>{if(t(b))return new Promise((c,d)=>{var e=new XMLHttpRequest;
e.open("GET",b,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var a=await fetch(b,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}console.log.bind(console);var z=console.error.bind(console),A,fa=!1,t=b=>b.startsWith("file://"),ha,ia,ja,ka,C,D,E,F,G,la,ma,na,oa,pa=!1,H=0,I=null;
function qa(b){n.onAbort?.(b);b="Aborted("+b+")";z(b);fa=!0;b=new WebAssembly.RuntimeError(b+". Build with -sASSERTIONS for more info.");ia?.(b);throw b;}var ra;async function sa(b){if(!A)try{var a=await ea(b);return new Uint8Array(a)}catch{}if(b==ra&&A)b=new Uint8Array(A);else if(q)b=q(b);else throw"both async and sync fetching of the wasm failed";return b}
async function ta(b,a){try{var c=await sa(b);return await WebAssembly.instantiate(c,a)}catch(d){z(`failed to asynchronously prepare wasm: ${d}`),qa(d)}}async function ua(b){var a=ra;if(!A&&"function"==typeof WebAssembly.instantiateStreaming&&!t(a)&&!ca)try{var c=fetch(a,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,b)}catch(d){z(`wasm streaming compile failed: ${d}`),z("falling back to ArrayBuffer instantiation")}return ta(a,b)}
var va=b=>{for(;0<b.length;)b.shift()(n)},wa=[],ya=[],za=()=>{var b=n.preRun.shift();ya.push(b)};class Aa{constructor(b){this.G=b-24}}var Ba=0,Ca=0,J={},Da=b=>{for(;b.length;){var a=b.pop();b.pop()(a)}};function K(b){return this.I(G[b>>2])}
var L={},M={},N={},O=class extends Error{constructor(b){super(b);this.name="InternalError"}},S=(b,a,c)=>{function d(f){f=c(f);if(f.length!==b.length)throw new O("Mismatched type converter count");for(var k=0;k<b.length;++k)P(b[k],f[k])}b.forEach(f=>N[f]=a);var e=Array(a.length),g=[],h=0;a.forEach((f,k)=>{M.hasOwnProperty(f)?e[k]=M[f]:(g.push(f),L.hasOwnProperty(f)||(L[f]=[]),L[f].push(()=>{e[k]=M[f];++h;h===g.length&&d(e)}))});0===g.length&&d(e)},T=b=>{for(var a="";;){var c=C[b++];if(!c)return a;
a+=String.fromCharCode(c)}},U=class extends Error{constructor(b){super(b);this.name="BindingError"}},Ea=b=>{throw new U(b);};function Fa(b,a,c={}){var d=a.name;if(!b)throw new U(`type "${d}" must have a positive integer typeid pointer`);if(M.hasOwnProperty(b)){if(c.na)return;throw new U(`Cannot register type '${d}' twice`);}M[b]=a;delete N[b];L.hasOwnProperty(b)&&(a=L[b],delete L[b],a.forEach(e=>e()))}function P(b,a,c={}){return Fa(b,a,c)}
var Ga=(b,a,c)=>{switch(a){case 1:return c?d=>ka[d]:d=>C[d];case 2:return c?d=>D[d>>1]:d=>E[d>>1];case 4:return c?d=>F[d>>2]:d=>G[d>>2];case 8:return c?d=>na[d>>3]:d=>oa[d>>3];default:throw new TypeError(`invalid integer width (${a}): ${b}`);}},Ha=b=>{throw new U(b.D.H.F.name+" instance already deleted");},Ia=!1,Ja=()=>{},V=b=>{if("undefined"===typeof FinalizationRegistry)return V=a=>a,b;Ia=new FinalizationRegistry(a=>{a=a.D;--a.count.value;0===a.count.value&&(a.K?a.O.P(a.K):a.H.F.P(a.G))});V=a=>
{var c=a.D;c.K&&Ia.register(a,{D:c},a);return a};Ja=a=>{Ia.unregister(a)};return V(b)},Ka=[];function La(){}
var Ma=(b,a)=>Object.defineProperty(a,"name",{value:b}),Na={},Oa=(b,a,c)=>{if(void 0===b[a].J){var d=b[a];b[a]=function(...e){if(!b[a].J.hasOwnProperty(e.length))throw new U(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${b[a].J})!`);return b[a].J[e.length].apply(this,e)};b[a].J=[];b[a].J[d.U]=d}},Pa=(b,a,c)=>{if(n.hasOwnProperty(b)){if(void 0===c||void 0!==n[b].J&&void 0!==n[b].J[c])throw new U(`Cannot register public name '${b}' twice`);Oa(n,b,b);if(n[b].J.hasOwnProperty(c))throw new U(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
n[b].J[c]=a}else n[b]=a,n[b].U=c},Qa=b=>{b=b.replace(/[^a-zA-Z0-9_]/g,"$");var a=b.charCodeAt(0);return 48<=a&&57>=a?`_${b}`:b};function Ra(b,a,c,d,e,g,h,f){this.name=b;this.constructor=a;this.T=c;this.P=d;this.M=e;this.ia=g;this.X=h;this.ha=f;this.pa=[]}
var Sa=(b,a,c)=>{for(;a!==c;){if(!a.X)throw new U(`Expected null or instance of ${c.name}, got an instance of ${a.name}`);b=a.X(b);a=a.M}return b},Ta=b=>{if(null===b)return"null";var a=typeof b;return"object"===a||"array"===a||"function"===a?b.toString():""+b};
function Ua(b,a){if(null===a){if(this.$)throw new U(`null is not a valid ${this.name}`);return 0}if(!a.D)throw new U(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.D.G)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);return Sa(a.D.G,a.D.H.F,this.F)}
function Va(b,a){if(null===a){if(this.$)throw new U(`null is not a valid ${this.name}`);if(this.Z){var c=this.aa();null!==b&&b.push(this.P,c);return c}return 0}if(!a||!a.D)throw new U(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.D.G)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Y&&a.D.H.Y)throw new U(`Cannot convert argument of type ${a.D.O?a.D.O.name:a.D.H.name} to parameter type ${this.name}`);c=Sa(a.D.G,a.D.H.F,this.F);if(this.Z){if(void 0===a.D.K)throw new U("Passing raw pointer to smart pointer is illegal");
switch(this.ua){case 0:if(a.D.O===this)c=a.D.K;else throw new U(`Cannot convert argument of type ${a.D.O?a.D.O.name:a.D.H.name} to parameter type ${this.name}`);break;case 1:c=a.D.K;break;case 2:if(a.D.O===this)c=a.D.K;else{var d=a.clone();c=this.qa(c,Wa(()=>d["delete"]()));null!==b&&b.push(this.P,c)}break;default:throw new U("Unsupporting sharing policy");}}return c}
function Xa(b,a){if(null===a){if(this.$)throw new U(`null is not a valid ${this.name}`);return 0}if(!a.D)throw new U(`Cannot pass "${Ta(a)}" as a ${this.name}`);if(!a.D.G)throw new U(`Cannot pass deleted object as a pointer of type ${this.name}`);if(a.D.H.Y)throw new U(`Cannot convert argument of type ${a.D.H.name} to parameter type ${this.name}`);return Sa(a.D.G,a.D.H.F,this.F)}
var Ya=(b,a,c)=>{if(a===c)return b;if(void 0===c.M)return null;b=Ya(b,a,c.M);return null===b?null:c.ha(b)},Za={},$a=(b,a)=>{if(void 0===a)throw new U("ptr should not be undefined");for(;b.M;)a=b.X(a),b=b.M;return Za[a]},ab=(b,a)=>{if(!a.H||!a.G)throw new O("makeClassHandle requires ptr and ptrType");if(!!a.O!==!!a.K)throw new O("Both smartPtrType and smartPtr must be specified");a.count={value:1};return V(Object.create(b,{D:{value:a,writable:!0}}))};
function bb(b,a,c,d,e,g,h,f,k,l,m){this.name=b;this.F=a;this.$=c;this.Y=d;this.Z=e;this.oa=g;this.ua=h;this.fa=f;this.aa=k;this.qa=l;this.P=m;e||void 0!==a.M?this.L=Va:(this.L=d?Ua:Xa,this.N=null)}
var cb=(b,a,c)=>{if(!n.hasOwnProperty(b))throw new O("Replacing nonexistent public symbol");void 0!==n[b].J&&void 0!==c?n[b].J[c]=a:(n[b]=a,n[b].U=c)},db=[],eb,W=(b,a)=>{b=T(b);var c;(c=db[a])||(db[a]=c=eb.get(a));if("function"!=typeof c)throw new U(`unknown function pointer with signature ${b}: ${a}`);return c};class gb extends Error{}
var ib=b=>{b=hb(b);var a=T(b);X(b);return a},jb=(b,a)=>{function c(g){e[g]||M[g]||(N[g]?N[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};a.forEach(c);throw new gb(`${b}: `+d.map(ib).join([", "]));},kb=(b,a)=>{for(var c=[],d=0;d<b;d++)c.push(G[a+4*d>>2]);return c};function lb(b){for(var a=1;a<b.length;++a)if(null!==b[a]&&void 0===b[a].N)return!0;return!1}
function mb(b,a,c,d,e,g){var h=a.length;if(2>h)throw new U("argTypes array size mismatch! Must at least get return value and 'this' types!");var f=null!==a[1]&&null!==c,k=lb(a);c=!a[0].ea;var l=a[0],m=a[1];d=[b,Ea,d,e,Da,l.I.bind(l),m?.L.bind(m)];for(e=2;e<h;++e)l=a[e],d.push(l.L.bind(l));if(!k)for(e=f?1:2;e<a.length;++e)null!==a[e].N&&d.push(a[e].N);k=lb(a);e=a.length-2;m=[];l=["fn"];f&&l.push("thisWired");for(h=0;h<e;++h)m.push(`arg${h}`),l.push(`arg${h}Wired`);m=m.join(",");l=l.join(",");m=`return function (${m}) {\n`;
k&&(m+="var destructors = [];\n");var r=k?"destructors":"null",w="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");f&&(m+=`var thisWired = toClassParamWire(${r}, this);\n`);for(h=0;h<e;++h){var u=`toArg${h}Wire`;m+=`var arg${h}Wired = ${u}(${r}, arg${h});\n`;w.push(u)}m+=(c||g?"var rv = ":"")+`invoker(${l});\n`;if(k)m+="runDestructors(destructors);\n";else for(h=f?1:2;h<a.length;++h)g=1===h?"thisWired":"arg"+(h-2)+"Wired",null!==a[h].N&&(m+=`${g}_dtor(${g});\n`,
w.push(`${g}_dtor`));c&&(m+="var ret = fromRetWire(rv);\nreturn ret;\n");a=(new Function(w,m+"}\n"))(...d);return Ma(b,a)}
var nb=b=>{b=b.trim();const a=b.indexOf("(");return-1===a?b:b.slice(0,a)},ob=[],Y=[0,1,,1,null,1,!0,1,!1,1],pb=b=>{9<b&&0===--Y[b+1]&&(Y[b]=void 0,ob.push(b))},qb=b=>{if(!b)throw new U(`Cannot use deleted val. handle = ${b}`);return Y[b]},Wa=b=>{switch(b){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const a=ob.pop()||Y.length;Y[a]=b;Y[a+1]=1;return a}},rb={name:"emscripten::val",I:b=>{var a=qb(b);pb(b);return a},L:(b,a)=>Wa(a),R:K,N:null},sb=(b,a)=>{switch(a){case 4:return function(c){return this.I(la[c>>
2])};case 8:return function(c){return this.I(ma[c>>3])};default:throw new TypeError(`invalid float width (${a}): ${b}`);}},tb=Object.assign({optional:!0},rb),ub="undefined"!=typeof TextDecoder?new TextDecoder:void 0,vb=(b,a,c,d)=>{c=a+c;if(d)return c;for(;b[a]&&!(a>=c);)++a;return a},wb=(b=0,a)=>{var c=C;a=vb(c,b,a,!0);if(16<a-b&&c.buffer&&ub)return ub.decode(c.subarray(b,a));for(var d="";b<a;){var e=c[b++];if(e&128){var g=c[b++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var h=c[b++]&
63;e=224==(e&240)?(e&15)<<12|g<<6|h:(e&7)<<18|g<<12|h<<6|c[b++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},xb="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,yb=(b,a,c)=>{b>>=1;a=vb(E,b,a/2,c);if(16<a-b&&xb)return xb.decode(E.subarray(b,a));for(c="";b<a;++b)c+=String.fromCharCode(E[b]);return c},zb=(b,a,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=a;c=c<2*b.length?c/2:b.length;for(var e=
0;e<c;++e)D[a>>1]=b.charCodeAt(e),a+=2;D[a>>1]=0;return a-d},Ab=b=>2*b.length,Bb=(b,a,c)=>{var d="";b>>=2;for(var e=0;!(e>=a/4);e++){var g=G[b+e];if(!g&&!c)break;d+=String.fromCodePoint(g)}return d},Cb=(b,a,c)=>{c??=2147483647;if(4>c)return 0;var d=a;c=d+c-4;for(var e=0;e<b.length;++e){var g=b.codePointAt(e);65535<g&&e++;F[a>>2]=g;a+=4;if(a+4>c)break}F[a>>2]=0;return a-d},Db=b=>{for(var a=0,c=0;c<b.length;++c)65535<b.codePointAt(c)&&c++,a+=4;return a},Eb=[],Fb=b=>{var a=Eb.length;Eb.push(b);return a},
Gb=(b,a)=>{for(var c=Array(b),d=0;d<b;++d){var e=d,g=G[a+4*d>>2],h=M[g];if(void 0===h)throw b=`${`parameter ${d}`} has unknown type ${ib(g)}`,new U(b);c[e]=h}return c},Hb=(b,a,c)=>{var d=[];b=b(d,c);d.length&&(G[a>>2]=Wa(d));return b},Ib={},Jb=b=>{var a=Ib[b];return void 0===a?T(b):a};
(()=>{let b=La.prototype;Object.assign(b,{isAliasOf:function(c){if(!(this instanceof La&&c instanceof La))return!1;var d=this.D.H.F,e=this.D.G;c.D=c.D;var g=c.D.H.F;for(c=c.D.G;d.M;)e=d.X(e),d=d.M;for(;g.M;)c=g.X(c),g=g.M;return d===g&&e===c},clone:function(){this.D.G||Ha(this);if(this.D.W)return this.D.count.value+=1,this;var c=V,d=Object,e=d.create,g=Object.getPrototypeOf(this),h=this.D;c=c(e.call(d,g,{D:{value:{count:h.count,V:h.V,W:h.W,G:h.G,H:h.H,K:h.K,O:h.O}}}));c.D.count.value+=1;c.D.V=!1;
return c},["delete"](){this.D.G||Ha(this);if(this.D.V&&!this.D.W)throw new U("Object already scheduled for deletion");Ja(this);var c=this.D;--c.count.value;0===c.count.value&&(c.K?c.O.P(c.K):c.H.F.P(c.G));this.D.W||(this.D.K=void 0,this.D.G=void 0)},isDeleted:function(){return!this.D.G},deleteLater:function(){this.D.G||Ha(this);if(this.D.V&&!this.D.W)throw new U("Object already scheduled for deletion");Ka.push(this);this.D.V=!0;return this}});const a=Symbol.dispose;a&&(b[a]=b["delete"])})();
Object.assign(bb.prototype,{ja(b){this.fa&&(b=this.fa(b));return b},da(b){this.P?.(b)},R:K,I:function(b){function a(){return this.Z?ab(this.F.T,{H:this.oa,G:c,O:this,K:b}):ab(this.F.T,{H:this,G:b})}var c=this.ja(b);if(!c)return this.da(b),null;var d=$a(this.F,c);if(void 0!==d){if(0===d.D.count.value)return d.D.G=c,d.D.K=b,d.clone();d=d.clone();this.da(b);return d}d=this.F.ia(c);d=Na[d];if(!d)return a.call(this);d=this.Y?d.ga:d.pointerType;var e=Ya(c,this.F,d.F);return null===e?a.call(this):this.Z?
ab(d.F.T,{H:d,G:e,O:this,K:b}):ab(d.F.T,{H:d,G:e})}});n.printErr&&(z=n.printErr);n.wasmBinary&&(A=n.wasmBinary);
var hb,Kb,X,Lb={f:(b,a,c)=>{var d=new Aa(b);G[d.G+16>>2]=0;G[d.G+4>>2]=a;G[d.G+8>>2]=c;Ba=b;Ca++;throw Ba;},o:()=>qa(""),g:b=>{var a=J[b];delete J[b];var c=a.elements,d=c.length,e=c.map(f=>f.ma).concat(c.map(f=>f.sa)),g=a.aa,h=a.P;S([b],e,f=>{c.forEach((k,l)=>{var m=f[l],r=k.ka,w=k.la,u=f[l+d],v=k.ra,y=k.ta;k.read=B=>m.I(r(w,B));k.write=(B,Q)=>{var x=[];v(y,B,u.L(x,Q));Da(x)}});return[{name:a.name,I:k=>{for(var l=Array(d),m=0;m<d;++m)l[m]=c[m].read(k);h(k);return l},L:(k,l)=>{if(d!==l.length)throw new TypeError(`Incorrect number of tuple elements for ${a.name}: expected=${d}, actual=${l.length}`);
for(var m=g(),r=0;r<d;++r)c[r].write(m,l[r]);null!==k&&k.push(h,m);return m},R:K,N:h}]})},i:(b,a,c,d,e)=>{a=T(a);d=0n===d;let g=h=>h;if(d){const h=8*c;g=f=>BigInt.asUintN(h,f);e=g(e)}P(b,{name:a,I:g,L:(h,f)=>{"number"==typeof f&&(f=BigInt(f));return f},R:Ga(a,c,!d),N:null})},s:(b,a,c,d)=>{a=T(a);P(b,{name:a,I:function(e){return!!e},L:function(e,g){return g?c:d},R:function(e){return this.I(C[e])},N:null})},m:(b,a,c,d,e,g,h,f,k,l,m,r,w)=>{m=T(m);g=W(e,g);f&&=W(h,f);l&&=W(k,l);w=W(r,w);var u=Qa(m);Pa(u,
function(){jb(`Cannot construct ${m} due to unbound types`,[d])});S([b,a,c],d?[d]:[],v=>{v=v[0];if(d){var y=v.F;var B=y.T}else B=La.prototype;v=Ma(m,function(...xa){if(Object.getPrototypeOf(this)!==Q)throw new U(`Use 'new' to construct ${m}`);if(void 0===x.S)throw new U(`${m} has no accessible constructor`);var fb=x.S[xa.length];if(void 0===fb)throw new U(`Tried to invoke ctor of ${m} with invalid number of parameters (${xa.length}) - expected (${Object.keys(x.S).toString()}) parameters instead!`);
return fb.apply(this,xa)});var Q=Object.create(B,{constructor:{value:v}});v.prototype=Q;var x=new Ra(m,v,Q,w,y,g,f,l);if(x.M){var R;(R=x.M).ba??(R.ba=[]);x.M.ba.push(x)}y=new bb(m,x,!0,!1,!1);R=new bb(m+"*",x,!1,!1,!1);B=new bb(m+" const*",x,!1,!0,!1);Na[b]={pointerType:R,ga:B};cb(u,v);return[y,R,B]})},l:(b,a,c,d,e,g)=>{var h=kb(a,c);e=W(d,e);S([],[b],f=>{f=f[0];var k=`constructor ${f.name}`;void 0===f.F.S&&(f.F.S=[]);if(void 0!==f.F.S[a-1])throw new U(`Cannot register multiple constructors with identical number of parameters (${a-
1}) for class '${f.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);f.F.S[a-1]=()=>{jb(`Cannot construct ${f.name} due to unbound types`,h)};S([],h,l=>{l.splice(1,0,null);f.F.S[a-1]=mb(k,l,null,e,g);return[]});return[]})},d:(b,a,c,d,e,g,h,f,k)=>{var l=kb(c,d);a=T(a);a=nb(a);g=W(e,g);S([],[b],m=>{function r(){jb(`Cannot call ${w} due to unbound types`,l)}m=m[0];var w=`${m.name}.${a}`;a.startsWith("@@")&&(a=Symbol[a.substring(2)]);f&&m.F.pa.push(a);
var u=m.F.T,v=u[a];void 0===v||void 0===v.J&&v.className!==m.name&&v.U===c-2?(r.U=c-2,r.className=m.name,u[a]=r):(Oa(u,a,w),u[a].J[c-2]=r);S([],l,y=>{y=mb(w,y,m,g,h,k);void 0===u[a].J?(y.U=c-2,u[a]=y):u[a].J[c-2]=y;return[]});return[]})},q:b=>P(b,rb),h:(b,a,c)=>{a=T(a);P(b,{name:a,I:d=>d,L:(d,e)=>e,R:sb(a,c),N:null})},w:(b,a,c,d,e,g,h)=>{var f=kb(a,c);b=T(b);b=nb(b);e=W(d,e);Pa(b,function(){jb(`Cannot call ${b} due to unbound types`,f)},a-1);S([],f,k=>{k=[k[0],null].concat(k.slice(1));cb(b,mb(b,k,
null,e,g,h),a-1);return[]})},b:(b,a,c,d,e)=>{a=T(a);let g=f=>f;if(0===d){var h=32-8*c;g=f=>f<<h>>>h;e=g(e)}P(b,{name:a,I:g,L:(f,k)=>k,R:Ga(a,c,0!==d),N:null})},a:(b,a,c)=>{function d(g){return new e(ka.buffer,G[g+4>>2],G[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][a];c=T(c);P(b,{name:c,I:d,R:d},{na:!0})},n:b=>{P(b,tb)},r:(b,a)=>{a=T(a);P(b,{name:a,I(c){var d=(d=c+4)?wb(d,G[c>>2]):"";X(c);return d},L(c,d){d instanceof
ArrayBuffer&&(d=new Uint8Array(d));var e,g="string"==typeof d;if(!(g||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new U("Cannot pass non-string to std::string");var h;if(g)for(e=h=0;e<d.length;++e){var f=d.charCodeAt(e);127>=f?h++:2047>=f?h+=2:55296<=f&&57343>=f?(h+=4,++e):h+=3}else h=d.length;e=h;h=Kb(4+e+1);f=h+4;G[h>>2]=e;if(g){if(g=f,f=e+1,e=C,0<f){f=g+f-1;for(var k=0;k<d.length;++k){var l=d.codePointAt(k);if(127>=l){if(g>=f)break;e[g++]=l}else if(2047>=l){if(g+1>=f)break;e[g++]=192|
l>>6;e[g++]=128|l&63}else if(65535>=l){if(g+2>=f)break;e[g++]=224|l>>12;e[g++]=128|l>>6&63;e[g++]=128|l&63}else{if(g+3>=f)break;e[g++]=240|l>>18;e[g++]=128|l>>12&63;e[g++]=128|l>>6&63;e[g++]=128|l&63;k++}}e[g]=0}}else C.set(d,f);null!==c&&c.push(X,h);return h},R:K,N(c){X(c)}})},e:(b,a,c)=>{c=T(c);if(2===a){var d=yb;var e=zb;var g=Ab}else d=Bb,e=Cb,g=Db;P(b,{name:c,I:h=>{var f=d(h+4,G[h>>2]*a,!0);X(h);return f},L:(h,f)=>{if("string"!=typeof f)throw new U(`Cannot pass non-string to C++ string type ${c}`);
var k=g(f),l=Kb(4+k+a);G[l>>2]=k/a;e(f,l+4,k+a);null!==h&&h.push(X,l);return l},R:K,N(h){X(h)}})},j:(b,a,c,d,e,g)=>{J[b]={name:T(a),aa:W(c,d),P:W(e,g),elements:[]}},c:(b,a,c,d,e,g,h,f,k)=>{J[b].elements.push({ma:a,ka:W(c,d),la:e,sa:g,ra:W(h,f),ta:k})},t:(b,a)=>{a=T(a);P(b,{ea:!0,name:a,I:()=>{},L:()=>{}})},k:(b,a,c)=>{var [d,...e]=Gb(b,a);a=d.L.bind(d);var g=e.map(k=>k.R.bind(k));b--;var h={toValue:qb};b=g.map((k,l)=>{var m=`argFromPtr${l}`;h[m]=k;return`${m}(args${l?"+"+8*l:""})`});switch(c){case 0:var f=
"toValue(handle)";break;case 2:f="new (toValue(handle))";break;case 3:f="";break;case 1:h.getStringOrSymbol=Jb,f="toValue(handle)[getStringOrSymbol(methodName)]"}f+=`(${b})`;d.ea||(h.toReturnWire=a,h.emval_returnValue=Hb,f=`return emval_returnValue(toReturnWire, destructorsRef, ${f})`);f=`return function (handle, methodName, destructorsRef, args) {\n  ${f}\n  }`;c=(new Function(Object.keys(h),f))(...Object.values(h));f=`methodCaller<(${e.map(k=>k.name)}) => ${d.name}>`;return Fb(Ma(f,c))},v:(b,a,
c,d,e)=>Eb[b](a,c,d,e),u:b=>{var a=qb(b);Da(a);pb(b)},p:()=>{qa("OOM")}},Z=await (async function(){function b(c){Z=c.exports;ja=Z.x;c=ja.buffer;ka=new Int8Array(c);D=new Int16Array(c);C=new Uint8Array(c);E=new Uint16Array(c);F=new Int32Array(c);G=new Uint32Array(c);la=new Float32Array(c);ma=new Float64Array(c);na=new BigInt64Array(c);oa=new BigUint64Array(c);eb=Z.A;c=Z;hb=c.z;Kb=c.B;X=c.C;H--;n.monitorRunDependencies?.(H);0==H&&I&&(c=I,I=null,c());return Z}H++;n.monitorRunDependencies?.(H);
var a={a:Lb};if(n.instantiateWasm)return new Promise(c=>{n.instantiateWasm(a,(d,e)=>{c(b(d,e))})});ra??=n.locateFile?n.locateFile?n.locateFile("worker_wasm.wasm",p):p+"worker_wasm.wasm":(new URL("worker_wasm.wasm",import.meta.url)).href;return b((await ua(a)).instance)}());
function Mb(){function b(){n.calledRun=!0;if(!fa){pa=!0;Z.y();ha?.(n);n.onRuntimeInitialized?.();if(n.postRun)for("function"==typeof n.postRun&&(n.postRun=[n.postRun]);n.postRun.length;){var a=n.postRun.shift();wa.push(a)}va(wa)}}if(0<H)I=Mb;else{if(n.preRun)for("function"==typeof n.preRun&&(n.preRun=[n.preRun]);n.preRun.length;)za();va(ya);0<H?I=Mb:n.setStatus?(n.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>n.setStatus(""),1);b()},1)):b()}}
if(n.preInit)for("function"==typeof n.preInit&&(n.preInit=[n.preInit]);0<n.preInit.length;)n.preInit.shift()();Mb();pa?moduleRtn=n:moduleRtn=new Promise((b,a)=>{ha=b;ia=a});
;return moduleRtn}export default Module;
